#!/usr/bin/env python

import rospy

from dynamic_reconfigure.server import Server
from parameter_server.cfg import followerConfig

def callback(config, level):
    rospy.loginfo("""Reconfigure Request: {time}, {radius}""".format(**config))
    return config

def clean_params():
    print('Running clean_params')
    try:
        rospy.delete_param('/circle/radius')
        rospy.delete_param('/circle/time')
    except KeyError:
        rospy.log("One or more parameters wasn't actually set")

if __name__ == "__main__":
    rospy.init_node('params_follower', anonymous = False)

    Srv = Server(followerConfig, callback)
    rospy.spin()

    rospy.on_shutdown(clean_params)
