#!/usr/bin/env python

import rospy

from dynamic_reconfigure.server import Server
from parameter_server.cfg import circleConfig

def callback(config, level):
    rospy.loginfo("""Reconfigure Request: {time}, {radius}""".format(**config))
    return config

def clean_params():
    print('Running clean_params')
    try:
        rospy.delete_param('/circle/radius')
        rospy.delete_param('/circle/time')
    except KeyError:
        rospy.log("One or more parameters wasn't actually set")

def callback_follower(config, level):
    rospy.loginfo("""Reconfigure Request: {Kp_u}, {Kp_r}, {umax}""".format(**config))
    return config

if __name__ == "__main__":
    rospy.init_node('params_circle', anonymous = False)

    Srv = Server(circleConfig, callback)
    rospy.spin()

    rospy.on_shutdown(clean_params)
