#!/usr/bin/env python

import rospy

from dynamic_reconfigure.server import Server
from parameter_server.cfg import circleConfig, followerConfig

def callback(config, level):
    rospy.loginfo("""Reconfigure Request: {time}, {radius}""".format(**config))
    return config

def callback_follower(config, level):
    rospy.loginfo("""Reconfigure Request: {Kp_u}, {Kp_r}, {umax}""".format(**config))
    return config

def clean_params():
    print('Running clean_params')
    try:
        rospy.delete_param('/circle/radius')
        rospy.delete_param('/circle/time')
    except KeyError:
        print("One or more parameters wasn't actually set")

if __name__ == "__main__":
    rospy.init_node('param_server', anonymous = False)

    #circSrv = Server(circleConfig, callback)
    follSrv = Server(followerConfig, callback_follower)
    rospy.spin()

    rospy.on_shutdown(clean_params)
